//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/DebugInputActions/DebugInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DebugInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DebugInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DebugInputActions"",
    ""maps"": [
        {
            ""name"": ""Debug"",
            ""id"": ""db2436b7-e3fe-47cf-9d3a-63808904900b"",
            ""actions"": [
                {
                    ""name"": ""LoadNextLevel"",
                    ""type"": ""Button"",
                    ""id"": ""1a7f8e23-ceed-4bad-9944-7154571fa1b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CollisionToggle"",
                    ""type"": ""Button"",
                    ""id"": ""84fbfec5-be27-4f16-8da5-2d3a4a1d4061"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""51dfad5e-eaef-4831-b297-042d771e47f0"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextLevel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88ba08be-c50d-4f7a-8e05-272f2d69a9fe"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CollisionToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_LoadNextLevel = m_Debug.FindAction("LoadNextLevel", throwIfNotFound: true);
        m_Debug_CollisionToggle = m_Debug.FindAction("CollisionToggle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Debug
    private readonly InputActionMap m_Debug;
    private List<IDebugActions> m_DebugActionsCallbackInterfaces = new List<IDebugActions>();
    private readonly InputAction m_Debug_LoadNextLevel;
    private readonly InputAction m_Debug_CollisionToggle;
    public struct DebugActions
    {
        private @DebugInputActions m_Wrapper;
        public DebugActions(@DebugInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @LoadNextLevel => m_Wrapper.m_Debug_LoadNextLevel;
        public InputAction @CollisionToggle => m_Wrapper.m_Debug_CollisionToggle;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void AddCallbacks(IDebugActions instance)
        {
            if (instance == null || m_Wrapper.m_DebugActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DebugActionsCallbackInterfaces.Add(instance);
            @LoadNextLevel.started += instance.OnLoadNextLevel;
            @LoadNextLevel.performed += instance.OnLoadNextLevel;
            @LoadNextLevel.canceled += instance.OnLoadNextLevel;
            @CollisionToggle.started += instance.OnCollisionToggle;
            @CollisionToggle.performed += instance.OnCollisionToggle;
            @CollisionToggle.canceled += instance.OnCollisionToggle;
        }

        private void UnregisterCallbacks(IDebugActions instance)
        {
            @LoadNextLevel.started -= instance.OnLoadNextLevel;
            @LoadNextLevel.performed -= instance.OnLoadNextLevel;
            @LoadNextLevel.canceled -= instance.OnLoadNextLevel;
            @CollisionToggle.started -= instance.OnCollisionToggle;
            @CollisionToggle.performed -= instance.OnCollisionToggle;
            @CollisionToggle.canceled -= instance.OnCollisionToggle;
        }

        public void RemoveCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDebugActions instance)
        {
            foreach (var item in m_Wrapper.m_DebugActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DebugActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    public interface IDebugActions
    {
        void OnLoadNextLevel(InputAction.CallbackContext context);
        void OnCollisionToggle(InputAction.CallbackContext context);
    }
}
